# Generated by Django 3.2.9 on 2021-12-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_alter_logger_execution_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='path',
            field=models.URLField(max_length=2048),
        ),
    ]
