# Generated by Django 3.2.9 on 2021-12-22 20:37

from django.db import migrations, models

import mainpage.phone_validator


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default='+380939399992', max_length=13, validators=[mainpage.phone_validator.validate_phone]),
            preserve_default=False,
        ),
    ]
