# Generated by Django 3.2.9 on 2021-12-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=64)),
                ('group_theme', models.CharField(max_length=64)),
                ('teacher', models.CharField(max_length=64)),
            ],
        ),
    ]
