# Generated by Django 3.2.9 on 2021-12-22 20:18

from django.db import migrations, models

import mainpage.phone_validator


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20211222_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default=380939399992, max_length=13, validators=[
                mainpage.phone_validator.validate_phone]),
            preserve_default=False,
        ),
    ]
